### ISSUE TITLE
Is there a way to convert NSAttributedString back to markdown?

### ISSUE THREAD

**Issue by hyouuu** [KristopherGBaker/Maaku#12]
Is there a way in Maaku to do that? If not, any recommended approaches? Sorry if it's a dumb question

**Comment by KristopherGBaker** [comment]
Hi,

That sounds like an interesting problem, but there isn't a way to directly do that in Maaku. Depending on your use case, I would consider working more directly with the gfm AST and converting to NSAttributedString or back to markdown as needed. If you really do need to convert from NSAttributedString to markdown, then you may need to write something custom. All of the Swift/Objective-C libraries I've seen only go from Markdown to NSAttributedString, not the other way around.

**Comment by hyouuu** [comment]
Thanks for the quick reply and pointers!!
