### ISSUE TITLE
unable to convert markdown text to attributed string

### ISSUE THREAD

**Issue by qwsdxcqwsdxc** [KristopherGBaker/Maaku#13]
There is no clear documentation for converting  markdown text to attributed string as there is no proper value can be given under Style argument in method attributedStringFromText:Style:

**Comment by qwsdxcqwsdxc** [comment]
This is the code : 
            let doc = try Document(text: markdownText)
            let finalText = doc.attributedText(style: ???) -----> unable to give a valid value
Is this the right way ?

**Comment by KristopherGBaker** [comment]
Hi,

`Style` is a protocol. You can create and use an instance of `DefaultStyle`, modifying the properties as needed, or you can create your own type that conforms to `Style`.

For your example, it could look like this:

```swift
var style = DefaultStyle()
// modify style properties as needed, for example
// style.colors.h1 = Color.darkGray
let doc = try Document(text: markdownText)
let finalText = doc.attributedText(style: style)
```

**Comment by qwsdxcqwsdxc** [comment]
It works ! Thanks for your reply
