### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by NightFlyer** [KristopherGBaker/Maaku#19]
I got the following problems when trying to use Maaku with XCode 10.1 on MacOS 10.13.6 (High Sierra):

.../test/.build/checkouts/Maaku.git-6543447715574722075/Sources/Maaku/CMark/CMDocument.swift:87:9: error: use of unresolved identifier 'cmark_gfm_core_extensions_ensure_registered'
        cmark_gfm_core_extensions_ensure_registered()
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../test/.build/checkouts/Maaku.git-6543447715574722075/Sources/Maaku/CMark/CMDocumentOption.swift:79:59: error: use of unresolved identifier 'CMARK_OPT_UNSAFE'; did you mean 'CMARK_OPT_SAFE'?
    public static let unsafe = CMDocumentOption(rawValue: CMARK_OPT_UNSAFE)
                                                          ^~~~~~~~~~~~~~~~
                                                          CMARK_OPT_SAFE
libcmark_gfm.CMARK_OPT_SAFE:1:12: note: 'CMARK_OPT_SAFE' declared here
public var CMARK_OPT_SAFE: Int32 { get }
           ^
.../test/.build/checkouts/Maaku.git-6543447715574722075/Sources/Maaku/CMark/CMDocumentOption.swift:72:70: error: use of unresolved identifier 'CMARK_OPT_FULL_INFO_STRING'
    public static let optFullInfoString = CMDocumentOption(rawValue: CMARK_OPT_FULL_INFO_STRING)
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
.../test/.build/checkouts/Maaku.git-6543447715574722075/Sources/Maaku/CMark/CMParser.swift:648:23: error: use of unresolved identifier 'cmark_gfm_extensions_get_table_columns'; did you mean 'cmarkextensions_get_table_columns'?
        let columns = cmark_gfm_extensions_get_table_columns(node.cmarkNode)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      cmarkextensions_get_table_columns
libcmark_gfm.cmarkextensions_get_table_columns:1:13: note: 'cmarkextensions_get_table_columns' declared here
public func cmarkextensions_get_table_columns(_ node: UnsafeMutablePointer<cmark_node>!) -> UInt16
            ^
.../test/.build/checkouts/Maaku.git-6543447715574722075/Sources/Maaku/CMark/CMParser.swift:649:26: error: use of unresolved identifier 'cmark_gfm_extensions_get_table_alignments'; did you mean 'cmarkextensions_get_table_alignments'?
        var alignments = cmark_gfm_extensions_get_table_alignments(node.cmarkNode)
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         cmarkextensions_get_table_alignments
libcmark_gfm.cmarkextensions_get_table_alignments:1:13: note: 'cmarkextensions_get_table_alignments' declared here
public func cmarkextensions_get_table_alignments(_ node: UnsafeMutablePointer<cmark_node>!) -> UnsafeMutablePointer<UInt8>!

**Comment by KristopherGBaker** [comment]
Are you still having this problem?

**Comment by NightFlyer** [comment]
I've managed to get things to work using cocoapods, so I'm not stuck.

In a couple of days when I have some free time, I can check again using Carthage or Packages.

**Comment by NightFlyer** [comment]
I think that everything is OK. This issue should probably be closed for now (and a new one opened if there is some problem in the future).
