### ISSUE TITLE
Carthage problems when building Maaku

### ISSUE THREAD

**Issue by NightFlyer** [KristopherGBaker/Maaku#36]
I can't get Maaku to compile via Carthage:
```
carthage update --platform iOS
*** Fetching Maaku
*** Fetching libcmark_gfm
*** Checking out libcmark_gfm at "0.29.1"
*** Checking out Maaku at "0.7.0"
*** xcodebuild output can be found in /var/folders/p8/30y00f_11kz9c9j5vwmbrdxw0000gn/T/carthage-xcodebuild.oRvmZd.log
*** Building scheme "libcmark_gfm" in libcmark_gfm.xcodeproj
*** Building scheme "libcmark_gfm-iOS" in libcmark_gfm.xcodeproj
*** Building scheme "Maaku" in Maaku.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/learmont/work/workspace/todo/swift/tmp/Carthage/Carthage/Checkouts/Maaku/Maaku.xcworkspace -scheme Maaku -configuration Release -derivedDataPath /Users/learmont/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Maaku/0.7.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/p8/30y00f_11kz9c9j5vwmbrdxw0000gn/T/Maaku SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/learmont/work/workspace/todo/swift/tmp/Carthage/Carthage/Checkouts/Maaku)
```

To recreate this problem:
1. Make a Cartfile that contains Maaku (`github "https://github.com/KristopherGBaker/Maaku.git"`)
1. run `carthage update --platform iOS`

I can't seem to upload the actual log file, but there are lots of error like:
```
error: Multiple commands produce '/Users/learmont/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Maaku/0.7.0/Build/Intermediates.noindex/ArchiveIntermediates/Maaku/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libcmark_gfm.framework':
1) Target 'libcmark_gfm-iOS9.0' has create directory command with output '/Users/learmont/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Maaku/0.7.0/Build/Intermediates.noindex/ArchiveIntermediates/Maaku/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libcmark_gfm.framework'
2) Target 'libcmark_gfm-tvOS9.0' has create directory command with output '/Users/learmont/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Maaku/0.7.0/Build/Intermediates.noindex/ArchiveIntermediates/Maaku/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libcmark_gfm.framework'

```
and stuff talking about duplicate output file.

**Comment by KristopherGBaker** [comment]
I'll take a look at this soon. I don't use Carthage much myself, but I should make sure it's working (and SwiftPM too).

**Comment by NightFlyer** [comment]
It's not holding me up, because I just build Maaku via Cocoapods and copied the frameworks into where Carthage would build them as a work-around for now, but it would be good to get it working if you're going to claim support for Carthage. (or remove Carthage support and only support Cocoa pods)

**Comment by KristopherGBaker** [comment]
Try again with 0.8.1. I switched the project to use the legacy Xcode build system for now, which seems to fix the issue with Carthage. I'll look into re-enabling the new build system later on.

**Comment by KristopherGBaker** [comment]
BTW, is Swift 5 / Xcode 10.2 okay for you (I noticed on one of the other issues you were using Xcode 10.1)? I guess there isn't necessarily a need to make Swift 5 required yet, and I'll switch it back if there's an issue.

**Comment by NightFlyer** [comment]
New stuff works just fine. Thanks.

Swift 5/Xcode 10.2 is fine. I finally got a new machine & so was able to update to Mojave and XCode 10.2
