### ISSUE TITLE
CMParser too restrictive

### ISSUE THREAD

**Issue by NightFlyer** [KristopherGBaker/Maaku#40]
The `CMParser` class could be more useful if it wasn't as restrictive. As far as I can tell, the only reason for  having the `CMDocument` be saved as a instance variable is so that you can call `parse` with no arguments. That doesn't seem all that useful. Maybe it's a design pattern you're following from someplace else?

I'd prefer that the `document` instance variable be removed, the initializer only take the delegate, and that the parse function change to:
`parse(subtree: CMNode, startingFootnoteIndex: Int32 = 0)`. There could also be a convenience function of `parse(document: CMDocument)` which calls `parse(subtree: document.node, startingFootnoteIndex: 0)` if you think that would be useful.

This makes the parser object useful for processing subtrees, so if someone just wants to get the objects dealing with a part of the tree, they can do that without having to "parse" the entire document and then figure out which parts of the returned `[items]` are actually what they want.

If `DocumentConverter` supplied `convert(cmNode: CMNode)` in addition to `convert(document: CMDocument)`, then anyone using mostly the CMark stuff is able to get relatively easy access to the `attributedText()` functionality by just converting over the CMNode that they want to display as attributed text into the equivalent Core object and then grabbing the attributed text.

That's basically what I'm experimenting with for my stuff right now. The problem with the Core stuff is that it uses `struct` and arrays, which are a problem if you want to manipulate the structure of the document and then write it out again. By relying on the CMark classes, I can (hopefully) read in the document, display it to the user using attributed text, manipulate the document in various ways, and then write it out using `renderCommonMark()`. 

I don't think that these changes in the design will adversely impact anyone, but will make the library more flexible for people who want to use it in different ways.

Note that this change isn't absolutely necessary for users, I just think that it would make the library more flexible. If you're really against changing `CMParser` in this way, then people can make due by essentially going back through snippets of CommonMark text like this:
```
let cmtext = nodeIWantAttributedTextFor.renderCommonMark(...)
let doc = Document(text: cmtext)
let realAttributedText = doc.items[1].attributedText(...)
```
But, it kind of seems a waste to convert the node to common mark text, then re-parse it, then generate the Block items just to get the attributed text.

**Comment by NightFlyer** [comment]
I'm happy to code this up and submit a pull request if it's something you think is OK. I just didn't want to do the work if it doesn't fit in your plans for the library and so would be rejected.

**Comment by KristopherGBaker** [comment]
There's no reason it has to remain the way it is. CMParser was originally based off of an Objective-C library that did something similar. I like what you're proposing, and I say go ahead with it.
