### ISSUE TITLE
Suggest renaming `destination`, `url`, and `title`

### ISSUE THREAD

**Issue by NightFlyer** [KristopherGBaker/Maaku#47]
I think it would be best to rename  `CMNode.destination`, `CMNode.url`, and `CMNode.title` to better capture that these are all link/image related items. I would suggest `linkDestination`, `linkUrl`, and `linkTitle`.

At the very least, I would suggest changing `title` to `linkTitle`, as the word "title" makes it confusing.

**Comment by NightFlyer** [comment]
I'll do the work if you agree on the names, or suggest other names.

**Comment by KristopherGBaker** [comment]
Go ahead your suggested names. 👍

**Comment by NightFlyer** [comment]
I'm thinking that leaving `Core/Link` and `Core/Image` fields alone, since the type name is already a qualifier. The problem with those fields in `CMNode` is that they're available for all nodes and so it's confusing (why wouldn't a heading node have a title?). There isn't that confusion when you're actually looking at a type that specifies what the underlying info refers to.
